In [1]:
import numpy as np

In [21]:
m=np.array([[12,23,34],[45,56],[67,78,89,100]])
print(m)
b=m.size
print(b)

[list([12, 23, 34]) list([45, 56]) list([67, 78, 89, 100])]
3


C:\Users\adhav\AppData\Local\Temp/ipykernel_15880/1110586012.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  m=np.array([[12,23,34],[45,56],[67,78,89,100]])


In [26]:
c=np.arange(1,100,7)
print(c)

[ 1  8 15 22 29 36 43 50 57 64 71 78 85 92 99]


In [36]:
d=c.reshape(5,3)
print(d)

[[ 1  8 15]
 [22 29 36]
 [43 50 57]
 [64 71 78]
 [85 92 99]]


In [39]:
c1=d[2:1,2:4]
print(c1)

[]


In [40]:
from numpy import random

In [42]:
a=random.randint(100)
print(a)

78


In [43]:
ab=random.randint(100,size=10)
print(ab)

[37 40  3 63 19  3 60 22 69 79]


In [45]:
d=random.randint(100,size=(3,5))
print(d)

[[37 80  0 64  3]
 [49 69 18 48  6]
 [38 97 22 83 39]]


In [52]:
e=random.choice(["swappy","amu","shreyu","ajju"])
print(e)



amu


In [53]:
f=random.rand()
print(f)

0.3633552186781872


In [54]:
g=random.rand(10)
print(g)

[0.73019088 0.09435561 0.83696951 0.78138755 0.79565952 0.60475703
 0.41124533 0.07696463 0.27840621 0.78228228]


In [55]:
h=random.rand(3,5)
print(h)

[[0.42092979 0.99278489 0.04001976 0.64806685 0.22274566]
 [0.52456851 0.71891541 0.58471788 0.69248469 0.44976953]
 [0.64085031 0.51664544 0.7019199  0.34242335 0.63158838]]


In [64]:
i=np.zeros(3*3)
print(i)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [66]:
j=np.ones(3,)
print(j)

[1. 1. 1.]
